Plugin:
  Command_Aliases: 'excellentshop,eshop'

Database:
  Table_Prefix: 'excellentshop'

Modules:
  virtual_shop:
    Enabled: true
    Name: Virtual Shop
  chest_shop:
    Enabled: true
    Name: Chest Shop
  auction:
    Enabled: true
    Name: Auction
